"""App-owned state for the clear-record web/service surface.

This subpackage is the **headless service**: the project registry, the
per-project glossary, meetings and their tape sets, background pipeline runs
and the artifacts they produce. It is usable with no web app — an MCP client or
a script can import it directly, and the same operations would drive an agent.

Only *app-owned* state lives here. Recordings, workspaces and archives stay in
user-chosen directories (ADR-0006/ADR-0007); the registry stores paths and
metadata, never audio blobs.
"""

from __future__ import annotations

from clear_record.core.diagnostics import log_event, logs_dir, read_recent
from clear_record.core.paths import (
    APP,
    REGISTRY_FILENAME,
    WORKSPACES_DIRNAME,
    config_path,
    registry_path,
    resolve_data_dir,
    resolve_workspace_root,
)
from clear_record.service.agent_drafts import (
    DRAFT_FILENAME,
    DRAFT_ITEM_SHAPE,
    DRAFT_SHAPE,
    DRAFT_STATE,
    REVIEW_DECISIONS,
    TASK_KINDS,
    Draft,
    Provenance,
    StaleVersion,
    UnreadableChain,
    Version,
    append_version,
    list_drafts,
    read_draft,
    record_review,
    start_draft,
    write_draft,
)
from clear_record.service.agent_review import (
    AGENT_DIRNAME,
    PROMOTERS,
    AgentDraftsOut,
    DraftView,
    MeetingAgent,
    MeetingAgentError,
    PromotionError,
    VersionView,
    describe_draft,
    promote_draft,
)
from clear_record.service.archive import archive_meeting, verify_archive
from clear_record.service.auto import (
    AutoChoice,
    AutoProbe,
    AutoRun,
    BACKEND_AUTO,
    BackendChoice,
    ModelNotOnDisk,
    NoBackendAvailable,
    available_backend_ids,
    probe_auto,
    resolve_auto,
    resolve_backend,
    resolve_run,
)
from clear_record.service.benchmark import (
    format_mib,
    format_rate,
    format_ratio,
    format_seconds,
    run_axes,
)
from clear_record.service.diagnostics import (
    BUNDLE_FILENAME,
    BundleFacts,
    build_bundle,
    collect_bundle,
    console_log_config,
)
from clear_record.service.glossary import (
    CONFIRMED,
    GlossarySnapshot,
    build_snapshot,
    canonical_terms,
    project_snapshot,
    snapshot_from_text,
    write_project_snapshot,
    write_snapshot,
)
from clear_record.service.hello_tape import (
    HELLO_PHRASES,
    HelloTape,
    hello_phrase,
    write_hello_tape,
)
from clear_record.service.managed import (
    DEFAULT_MAX_UPLOAD_BYTES,
    DisallowedExtension,
    InsufficientSpace,
    UnsafeFilename,
    UploadRejected,
    UploadTooLarge,
    delete_tape,
    ensure_managed_workspace,
    is_managed,
    managed_root,
    max_upload_bytes,
    meeting_storage,
    precheck_upload,
    sanitize_filename,
    upload_tape,
    workspace_usage,
)
from clear_record.service.lifecycle import (
    ACTIVE_RUN_STATUSES,
    RESUMABLE_STATUSES,
    RESTART_REASON,
    RUN_FAILED,
    RUN_FINISHED,
    RUN_IN_FLIGHT,
    RUN_ORIGINS,
    RUN_STARTED,
    RUN_STATUSES,
    TERMINAL_STATUSES,
)
from clear_record.service.models import (
    MEETING_STATUSES,
    TERM_AUTHORS,
    TERM_STATUSES,
    Archive,
    Artifact,
    GlossaryTerm,
    Meeting,
    PipelineRun,
    Project,
    RecordingSet,
    Tape,
)
from clear_record.service.runs import (
    HEARTBEAT_INTERVAL_S,
    HEARTBEAT_STALE_S,
    PipelineOptions,
    RunManager,
    RunState,
    RunSummary,
    collect_artifacts,
    cost_of,
    estimate_eta_s,
    workspace_run_meeting,
)
from clear_record.service.run_options import (
    MalformedRunOptions,
    RunOptionsRow,
    read_run_options,
)
from clear_record.service.schemas import (
    ArchiveOut,
    ArtifactOut,
    EventOut,
    MeetingOut,
    MeetingTapesOut,
    ProjectCountOut,
    ProjectOut,
    ProvenanceOut,
    RunOut,
    Shape,
    TapeOut,
    TapeSetOut,
    TermOut,
    TranscriptOut,
    out_model,
)
from clear_record.service.store import Registry, RegistryLocked
from clear_record.service.transcript import TranscriptSlice, read_transcript
from clear_record.service.webhooks import (
    ALL_EVENTS,
    ARCHIVE_CREATED,
    EMITTED_EVENTS,
    FUTURE_EVENTS,
    SIGNATURE_HEADER,
    TRANSCRIPT_READY,
    Delivery,
    WebhookConfig,
    WebhookEmitter,
    WebhookEndpoint,
    WebhookEvent,
    load_webhook_config,
    resolve_endpoints,
    sign,
)

# The guided agent flow and its hello-world acceptance/diagnostic check
# Imported last on purpose: it reaches clear_record.service.setup,
# which is not part of this package's eager import graph, so every module it
# needs is already loaded when this line runs.
from clear_record.service.agent_flow import (
    HELLO_CHECK_DIRNAME,
    LEG_BACKEND,
    LEG_MODEL,
    LEG_OK,
    LEG_TRANSCRIBE,
    LEG_TTS,
    TRANSCRIPT_TOOL,
    HelloCheck,
    run_hello_check,
)

__all__ = [
    "ACTIVE_RUN_STATUSES",
    "AGENT_DIRNAME",
    "ALL_EVENTS",
    "APP",
    "ARCHIVE_CREATED",
    "AgentDraftsOut",
    "Archive",
    "ArchiveOut",
    "Artifact",
    "ArtifactOut",
    "AutoChoice",
    "AutoProbe",
    "AutoRun",
    "BACKEND_AUTO",
    "BUNDLE_FILENAME",
    "BackendChoice",
    "BundleFacts",
    "CONFIRMED",
    "DEFAULT_MAX_UPLOAD_BYTES",
    "Delivery",
    "DisallowedExtension",
    "DraftView",
    "EMITTED_EVENTS",
    "EventOut",
    "FUTURE_EVENTS",
    "GlossarySnapshot",
    "GlossaryTerm",
    "HEARTBEAT_INTERVAL_S",
    "HEARTBEAT_STALE_S",
    "HELLO_PHRASES",
    "HelloTape",
    "InsufficientSpace",
    "MEETING_STATUSES",
    "MalformedRunOptions",
    "Meeting",
    "MeetingAgent",
    "MeetingAgentError",
    "MeetingOut",
    "MeetingTapesOut",
    "ModelNotOnDisk",
    "NoBackendAvailable",
    "PROMOTERS",
    "PipelineOptions",
    "PipelineRun",
    "Project",
    "ProjectCountOut",
    "ProjectOut",
    "PromotionError",
    "ProvenanceOut",
    "REGISTRY_FILENAME",
    "RESTART_REASON",
    "RUN_FAILED",
    "RUN_FINISHED",
    "RUN_ORIGINS",
    "RUN_STARTED",
    "RUN_STATUSES",
    "RecordingSet",
    "Registry",
    "RegistryLocked",
    "RESUMABLE_STATUSES",
    "RUN_IN_FLIGHT",
    "RunManager",
    "RunOptionsRow",
    "RunOut",
    "RunState",
    "RunSummary",
    "SIGNATURE_HEADER",
    "Shape",
    "TERMINAL_STATUSES",
    "TERM_AUTHORS",
    "TERM_STATUSES",
    "TRANSCRIPT_READY",
    "Tape",
    "TapeOut",
    "TapeSetOut",
    "TermOut",
    "TranscriptOut",
    "TranscriptSlice",
    "UnsafeFilename",
    "UploadRejected",
    "UploadTooLarge",
    "WORKSPACES_DIRNAME",
    "WebhookConfig",
    "WebhookEmitter",
    "WebhookEndpoint",
    "WebhookEvent",
    "archive_meeting",
    "available_backend_ids",
    "build_bundle",
    "build_snapshot",
    "canonical_terms",
    "collect_artifacts",
    "collect_bundle",
    "config_path",
    "console_log_config",
    "cost_of",
    "delete_tape",
    "ensure_managed_workspace",
    "estimate_eta_s",
    "format_mib",
    "format_rate",
    "format_ratio",
    "format_seconds",
    "is_managed",
    "load_webhook_config",
    "log_event",
    "logs_dir",
    "managed_root",
    "max_upload_bytes",
    "meeting_storage",
    "out_model",
    "precheck_upload",
    "probe_auto",
    "project_snapshot",
    "read_recent",
    "read_run_options",
    "read_transcript",
    "registry_path",
    "resolve_auto",
    "resolve_backend",
    "resolve_data_dir",
    "resolve_endpoints",
    "resolve_run",
    "resolve_workspace_root",
    "run_axes",
    "sanitize_filename",
    "sign",
    "snapshot_from_text",
    "upload_tape",
    "verify_archive",
    "workspace_run_meeting",
    "workspace_usage",
    "write_hello_tape",
    "write_project_snapshot",
    "write_snapshot",
    # The draft store: a version chain with author provenance (ADR-0031) —
    # appended to keep the export block's merge surface minimal.
    "DRAFT_FILENAME",
    "DRAFT_ITEM_SHAPE",
    "DRAFT_SHAPE",
    "DRAFT_STATE",
    "Draft",
    "Provenance",
    "REVIEW_DECISIONS",
    "StaleVersion",
    "TASK_KINDS",
    "UnreadableChain",
    "Version",
    "VersionView",
    "append_version",
    "describe_draft",
    "hello_phrase",
    "list_drafts",
    "promote_draft",
    "read_draft",
    "record_review",
    "start_draft",
    "write_draft",
    # Hello-world acceptance/diagnostic check — appended for the
    # same minimal-merge-surface reason as the agent-task block above.
    "HELLO_CHECK_DIRNAME",
    "LEG_BACKEND",
    "LEG_MODEL",
    "LEG_OK",
    "LEG_TRANSCRIBE",
    "LEG_TTS",
    "TRANSCRIPT_TOOL",
    "HelloCheck",
    "run_hello_check",
]
