"""App-owned state for the clear-record web/service surface.

This subpackage is the **headless service**: the project registry, the
per-project glossary, meetings and their tape sets, background pipeline runs
and the artifacts they produce. It is usable with no web app — an MCP client or
a script can import it directly, and the same operations would drive an agent.

Only *app-owned* state lives here. Recordings, workspaces and archives stay in
user-chosen directories (ADR-0006/ADR-0007); the registry stores paths and
metadata, never audio blobs.
"""

from __future__ import annotations

from clear_record.core.diagnostics import log_event, logs_dir, read_recent
from clear_record.service.agent import (
    ENV_API_KEY_ENV,
    ENV_ENDPOINT,
    ENV_MODEL,
    ENV_TIMEOUT,
    REVIEW_STATES,
    AgentConfig,
    AgentConfigError,
    CommandRunner,
    Draft,
    EndpointRunner,
    Provenance,
    Runner,
    RunnerError,
    RunnerOutput,
    RunnerRequest,
    accept_draft,
    default_config,
    load_agent_config,
    read_draft,
    reject_draft,
    reset_default_config,
    run_task,
)
from clear_record.service.agent_tasks import (
    CONTRACTS,
    PIPELINES,
    TASK_INPUTS,
    TASK_KINDS,
    AgentTask,
    AgentTaskError,
    OutputContract,
    OutputContractError,
    TaskStep,
    build_task,
    canonical_payload,
    context_hash,
    contract_for,
    glossary_collection_task,
    minutes_task,
    plan_for,
    prompt_hash,
    render_prompt,
    transcript_check_task,
)
from clear_record.service.archive import archive_meeting, verify_archive
from clear_record.service.auto import (
    AutoChoice,
    AutoProbe,
    AutoRun,
    BACKEND_AUTO,
    BackendChoice,
    ModelNotOnDisk,
    NoBackendAvailable,
    available_backend_ids,
    probe_auto,
    resolve_auto,
    resolve_backend,
    resolve_run,
)
from clear_record.service.diagnostics import (
    BUNDLE_FILENAME,
    BundleFacts,
    build_bundle,
    collect_bundle,
    console_log_config,
)
from clear_record.service.glossary import (
    CONFIRMED,
    GlossarySnapshot,
    build_snapshot,
    canonical_terms,
    project_snapshot,
    snapshot_from_text,
    write_project_snapshot,
    write_snapshot,
)
from clear_record.service.managed import (
    DEFAULT_MAX_UPLOAD_BYTES,
    DisallowedExtension,
    InsufficientSpace,
    UnsafeFilename,
    UploadRejected,
    UploadTooLarge,
    delete_tape,
    ensure_managed_workspace,
    is_managed,
    managed_root,
    max_upload_bytes,
    meeting_storage,
    precheck_upload,
    sanitize_filename,
    upload_tape,
    workspace_usage,
)
from clear_record.service.models import (
    MEETING_STATUSES,
    RUN_STATUSES,
    TERM_AUTHORS,
    TERM_STATUSES,
    Archive,
    Artifact,
    GlossaryTerm,
    Meeting,
    PipelineRun,
    Project,
    RecordingSet,
    Tape,
)
from clear_record.service.paths import (
    APP,
    REGISTRY_FILENAME,
    WORKSPACES_DIRNAME,
    config_path,
    registry_path,
    resolve_data_dir,
    resolve_workspace_root,
)
from clear_record.service.runs import (
    PipelineOptions,
    RESTART_REASON,
    RunManager,
    RunState,
    collect_artifacts,
)
from clear_record.service.store import SCHEMA_VERSION, Registry
from clear_record.service.transcript import TranscriptSlice, read_transcript
from clear_record.service.webhooks import (
    ALL_EVENTS,
    ARCHIVE_CREATED,
    EMITTED_EVENTS,
    FUTURE_EVENTS,
    RUN_FAILED,
    RUN_FINISHED,
    RUN_STARTED,
    SIGNATURE_HEADER,
    TRANSCRIPT_READY,
    Delivery,
    WebhookConfig,
    WebhookEmitter,
    WebhookEndpoint,
    WebhookEvent,
    load_webhook_config,
    resolve_endpoints,
    sign,
)

__all__ = [
    "ALL_EVENTS",
    "APP",
    "ARCHIVE_CREATED",
    "Archive",
    "Artifact",
    "AutoChoice",
    "AutoProbe",
    "AutoRun",
    "BACKEND_AUTO",
    "BUNDLE_FILENAME",
    "BackendChoice",
    "BundleFacts",
    "CONFIRMED",
    "DEFAULT_MAX_UPLOAD_BYTES",
    "Delivery",
    "DisallowedExtension",
    "EMITTED_EVENTS",
    "FUTURE_EVENTS",
    "GlossarySnapshot",
    "GlossaryTerm",
    "InsufficientSpace",
    "MEETING_STATUSES",
    "Meeting",
    "ModelNotOnDisk",
    "NoBackendAvailable",
    "PipelineOptions",
    "PipelineRun",
    "Project",
    "REGISTRY_FILENAME",
    "RESTART_REASON",
    "RUN_FAILED",
    "RUN_FINISHED",
    "RUN_STARTED",
    "RUN_STATUSES",
    "RecordingSet",
    "Registry",
    "RunManager",
    "RunState",
    "SCHEMA_VERSION",
    "SIGNATURE_HEADER",
    "TERM_AUTHORS",
    "TERM_STATUSES",
    "TRANSCRIPT_READY",
    "Tape",
    "TranscriptSlice",
    "UnsafeFilename",
    "UploadRejected",
    "UploadTooLarge",
    "WORKSPACES_DIRNAME",
    "WebhookConfig",
    "WebhookEmitter",
    "WebhookEndpoint",
    "WebhookEvent",
    "archive_meeting",
    "available_backend_ids",
    "build_bundle",
    "build_snapshot",
    "canonical_terms",
    "collect_artifacts",
    "collect_bundle",
    "config_path",
    "console_log_config",
    "delete_tape",
    "ensure_managed_workspace",
    "is_managed",
    "load_webhook_config",
    "log_event",
    "logs_dir",
    "managed_root",
    "max_upload_bytes",
    "meeting_storage",
    "precheck_upload",
    "probe_auto",
    "project_snapshot",
    "read_recent",
    "read_transcript",
    "registry_path",
    "resolve_auto",
    "resolve_backend",
    "resolve_data_dir",
    "resolve_endpoints",
    "resolve_run",
    "resolve_workspace_root",
    "sanitize_filename",
    "sign",
    "snapshot_from_text",
    "upload_tape",
    "verify_archive",
    "workspace_usage",
    "write_project_snapshot",
    "write_snapshot",
    # Agent-task runner seam (ADR-0018) — appended to keep the export block's
    # merge surface minimal.
    "AgentConfig",
    "AgentConfigError",
    "AgentTask",
    "AgentTaskError",
    "CONTRACTS",
    "CommandRunner",
    "Draft",
    "ENV_API_KEY_ENV",
    "ENV_ENDPOINT",
    "ENV_MODEL",
    "ENV_TIMEOUT",
    "EndpointRunner",
    "OutputContract",
    "OutputContractError",
    "PIPELINES",
    "Provenance",
    "REVIEW_STATES",
    "Runner",
    "RunnerError",
    "RunnerOutput",
    "RunnerRequest",
    "TASK_INPUTS",
    "TASK_KINDS",
    "TaskStep",
    "accept_draft",
    "build_task",
    "canonical_payload",
    "context_hash",
    "contract_for",
    "default_config",
    "glossary_collection_task",
    "load_agent_config",
    "minutes_task",
    "plan_for",
    "prompt_hash",
    "read_draft",
    "reject_draft",
    "render_prompt",
    "reset_default_config",
    "run_task",
    "transcript_check_task",
]
